/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-02 11:09:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import webproject.JDBCKonnekt;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/CSRelated/AndroidDeveloping/lab2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/javawebproj/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1275630142000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1606141566326L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("webproject.JDBCKonnekt");
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>INDEX | Student Management System</title>\r\n");
      out.write("\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("\t      function checkUsername()\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t          var flag = true;\r\n");
      out.write("\t          var element = document.getElementById(\"username\").value;\r\n");
      out.write("\t          var regNumber = /^.{0,10}$/ ;\r\n");
      out.write("\t          if(element==\"\"||element==null) {\r\n");
      out.write("\t              return false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          else if(!regNumber.test(element)) {\r\n");
      out.write("\t              alert(\"Username's length should be no more than 10!\");\r\n");
      out.write("\t              flag = false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          if(flag) document.getElementById(\"usernamespan\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:green;font-size:15px' <b>VALID</b> </font>\"\r\n");
      out.write("\t          else document.getElementById(\"usernamespan\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:red;font-size:15px' <b>INVALID</b> </font>\"\r\n");
      out.write("\t          return flag;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t      function checkUsername2()\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t          var flag = true;\r\n");
      out.write("\t          var element = document.getElementById(\"username2\").value;\r\n");
      out.write("\t          var regNumber = /^.{0,10}$/ ;\r\n");
      out.write("\t          if(element==\"\"||element==null) {\r\n");
      out.write("\t              return false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          else if(!regNumber.test(element)) {\r\n");
      out.write("\t              alert(\"Username's length should be no more than 10!\");\r\n");
      out.write("\t              flag = false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          if(flag) document.getElementById(\"usernamespan2\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:green;font-size:15px' <b>VALID</b> </font>\"\r\n");
      out.write("\t          else document.getElementById(\"usernamespan2\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:red;font-size:15px' <b>INVALID</b> </font>\"\r\n");
      out.write("\t          return flag;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t      function checkUsername3()\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t          var flag = true;\r\n");
      out.write("\t          var element = document.getElementById(\"username3\").value;\r\n");
      out.write("\t          var regNumber = /^.{0,10}$/ ;\r\n");
      out.write("\t          if(element==\"\"||element==null) {\r\n");
      out.write("\t              return false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          else if(!regNumber.test(element)) {\r\n");
      out.write("\t              alert(\"Username's length should be no more than 10!\");\r\n");
      out.write("\t              flag = false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          if(flag) document.getElementById(\"usernamespan3\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:green;font-size:15px' <b>VALID</b> </font>\"\r\n");
      out.write("\t          else document.getElementById(\"usernamespan3\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:red;font-size:15px' <b>INVALID</b> </font>\"\r\n");
      out.write("\t          return flag;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("\t      function checkUsername4()\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t          var flag = true;\r\n");
      out.write("\t          var element = document.getElementById(\"username4\").value;\r\n");
      out.write("\t          var regNumber = /^.{0,10}$/ ;\r\n");
      out.write("\t          if(element==\"\"||element==null) {\r\n");
      out.write("\t              return false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          else if(!regNumber.test(element)) {\r\n");
      out.write("\t              alert(\"Username's length should be no more than 10!\");\r\n");
      out.write("\t              flag = false;\r\n");
      out.write("\t          }\r\n");
      out.write("\t          if(flag) document.getElementById(\"usernamespan4\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:green;font-size:15px' <b>VALID</b> </font>\"\r\n");
      out.write("\t          else document.getElementById(\"usernamespan4\").innerHTML=\r\n");
      out.write("\t        \t  \"<font style='color:red;font-size:15px' <b>INVALID</b> </font>\"\r\n");
      out.write("\t          return flag;\r\n");
      out.write("\t      }\r\n");
      out.write("\t      \r\n");
      out.write("          function checkName()\r\n");
      out.write("\t\t  {\r\n");
      out.write("              var flag = true;\r\n");
      out.write("              var element = document.getElementById(\"name\").value;\r\n");
      out.write("              var regNumber = /^.{0,10}$/ ;\r\n");
      out.write("              if(element==\"\"||element==null){\r\n");
      out.write("                  return false;\r\n");
      out.write("              }\r\n");
      out.write("              if(!regNumber.test(element)) {\r\n");
      out.write("                  alert(\"Name's length should be no more than 10!\");\r\n");
      out.write("                  flag = false;\r\n");
      out.write("              }\r\n");
      out.write("              if(flag) document.getElementById(\"namespan\").innerHTML=\r\n");
      out.write("            \t  \"<font style='color:green;font-size:15px' <b>VALID</b> </font>\"\r\n");
      out.write("              else document.getElementById(\"namespan\").innerHTML=\r\n");
      out.write("            \t  \"<font style='color:red;font-size:15px' <b>INVALID</b> </font>\"\r\n");
      out.write("              return flag;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function checkAge()\r\n");
      out.write("\t\t  {\r\n");
      out.write("              var flag = true;\r\n");
      out.write("              var element = document.getElementById(\"age\").value;\r\n");
      out.write("              var regNumber = /^[0-9]+$/ ;\r\n");
      out.write("              if(element==null||element==\"\") return false;\r\n");
      out.write("              if(!regNumber.test(element)) {\r\n");
      out.write("                  alert(\"Age's type should be integer!\");\r\n");
      out.write("                  flag = false;\r\n");
      out.write("              }\r\n");
      out.write("              if(flag) document.getElementById(\"agespan\").innerHTML=\r\n");
      out.write("                  \"<font style='color:green;font-size:15px' <b>VALID</b> </font>\"\r\n");
      out.write("              else document.getElementById(\"agespan\").innerHTML=\r\n");
      out.write("                  \"<font style='color:red;font-size:15px' <b>INVALID</b> </font>\"\r\n");
      out.write("              return flag;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          function checkTeleno()\r\n");
      out.write("          {\r\n");
      out.write("              var flag = true;\r\n");
      out.write("              var element = document.getElementById(\"teleno\").value;\r\n");
      out.write("              var regNumber = /^1[3456789]\\d{9}$/ ;\t\t\t\t\t//This is how teleno works\r\n");
      out.write("              if(element==\"\"||element==null) return flag;\r\n");
      out.write("              if(!regNumber.test(element)) {\r\n");
      out.write("                  alert(\"Telenum's format is wrong!\");\r\n");
      out.write("                  flag = false;\r\n");
      out.write("              }\r\n");
      out.write("              if(flag) document.getElementById(\"telenospan\").innerHTML=\r\n");
      out.write("            \t  \"<font style='color:green;font-size:15px' <b>VALID</b> </font>\"\r\n");
      out.write("              else document.getElementById(\"telenospan\").innerHTML=\r\n");
      out.write("            \t  \"<font style='color:red;font-size:15px' <b>INVALID</b> </font>\"\r\n");
      out.write("              return flag;\r\n");
      out.write("          }\r\n");
      out.write("          function checkSubmit1() {\r\n");
      out.write("              if(document.getElementById(\"username\").value==null||document.getElementById(\"username\").value==\"\"){\r\n");
      out.write("                  alert(\"Please input person'username !\");\r\n");
      out.write("                  document.getElementById(\"usernamespan\").innerHTML=\r\n");
      out.write("                      \"<font style='color:red;font-size:15px' <b>username is empty</b> </font>\"\r\n");
      out.write("                  return false;\r\n");
      out.write("              }\r\n");
      out.write("              if (document.getElementById(\"name\").value==null||document.getElementById(\"name\").value==\"\"){\r\n");
      out.write("                  alert(\"Please input person'name!\");\r\n");
      out.write("                  document.getElementById(\"namespan\").innerHTML=\r\n");
      out.write("                      \"<font style='color:red;font-size:15px' <b>name is empty</b> </font>\"\r\n");
      out.write("                  return false;\r\n");
      out.write("              }\r\n");
      out.write("              var flag = checkTelenum()&&checkAge()&&checkUsername1()&&checkName();\r\n");
      out.write("              if(!flag){\r\n");
      out.write("                  alert(\"Submit Error!\")\r\n");
      out.write("              }\r\n");
      out.write("              return flag;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          function checkSubmit2() {\r\n");
      out.write("        \t  if(document.getElementById(\"username2\").value==null||document.getElementById(\"username2\").value==\"\"){\r\n");
      out.write("                  alert(\"Please input username !\");\r\n");
      out.write("                  document.getElementById(\"usernamespan2\").innerHTML=\r\n");
      out.write("                      \"<font style='color:red;font-size:15px' <b>username is empty</b> </font>\"\r\n");
      out.write("                  return false;\r\n");
      out.write("              }\r\n");
      out.write("              var flag = checkUsername2()\r\n");
      out.write("              if(!flag){\r\n");
      out.write("                  alert(\"Submit Error!\")\r\n");
      out.write("              }\r\n");
      out.write("              return flag;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function checkSubmit3() {\r\n");
      out.write("        \t  if(document.getElementById(\"username3\").value==null||document.getElementById(\"username3\").value==\"\"){\r\n");
      out.write("                  alert(\"Please input username !\");\r\n");
      out.write("                  document.getElementById(\"usernamespan3\").innerHTML=\r\n");
      out.write("                      \"<font style='color:red;font-size:15px' <b>username is empty</b> </font>\"\r\n");
      out.write("                  return false;\r\n");
      out.write("              }\r\n");
      out.write("              var flag = checkUsername3()\r\n");
      out.write("              if(!flag){\r\n");
      out.write("                  alert(\"Submit Error!\")\r\n");
      out.write("              }\r\n");
      out.write("              return flag;\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          function checkPassword()\r\n");
      out.write("          {\r\n");
      out.write("        \t  if (document.getElementById(\"username4\").value==null||document.getElementById(\"username4\").value==\"\"||!checkUsername4()){\r\n");
      out.write("                  alert(\"Username invalid!\");\r\n");
      out.write("                  document.getElementById(\"usernamespan4\").innerHTML=\r\n");
      out.write("                      \"<font style='color:red;font-size:15px' <b>name is empty</b> </font>\"\r\n");
      out.write("                  return false;\r\n");
      out.write("              }\r\n");
      out.write("          }\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

        JDBCKonnekt jk = new JDBCKonnekt();
        application.setAttribute("jk",jk);

      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<center> <h3>Insert Person Info</h3> </center>\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addPersonServlet\" onsubmit=\"return checkSubmit1()\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">User Name </label><span id=\"usernamespan\"></span>\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\" size=\"25\" maxlength=\"15\" value=\"\" onblur=\"checkUsername()\" align=\"center\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">Name </label><span id=\"namespan\"></span>\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" size=\"25\" maxlength=\"20\" value=\"\" onblur=\"checkName()\" align=\"center\" placeholder=\"type name here\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">Age </label><span id=\"agespan\"></span>\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"age\" name=\"age\" size=\"25\" maxlength=\"4\" value=\"\" onblur=\"checkAge()\" align=\"center\" placeholder=\"type current age here\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">Phone Number </label><span id=\"telenospan\"></span>\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"teleno\" name=\"teleno\"  size=\"25\" maxlength=\"20\" value=\"\" onblur=\"checkTeleno()\" align=\"center\" placeholder=\"type phone number here\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\" style=\"text-align: center\">\r\n");
      out.write("\t<center>\r\n");
      out.write("              <input class=\"btn btn-primary\" type=\"submit\" value=\"SUBMIT\" />\r\n");
      out.write("              <input class=\"btn btn-default\" type=\"reset\" value=\"RESET\" />\r\n");
      out.write("    </center>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("<div class=\"container\">    \r\n");
      out.write("<center> <h3>Delete Users</h3> </center>\r\n");
      out.write("\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/delUserServlet\" onsubmit=\"return checkSubmit2()\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">User Name </label><span id=\"usernamespan2\"></span>\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"username2\" name=\"username2\" size=\"25\" maxlength=\"15\" value=\"\" onblur=\"checkUsername2()\" align=\"center\" placeholder=\"type user name here\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-group\" style=\"text-align: center\">\r\n");
      out.write("\t<center>\r\n");
      out.write("              <input class=\"btn btn-primary\" type=\"submit\" value=\"SUBMIT\" />\r\n");
      out.write("              <input class=\"btn btn-default\" type=\"reset\" value=\"RESET\" />\r\n");
      out.write("    </center>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\"> \r\n");
      out.write("<center> <h3>Delete Person</h3> </center>\r\n");
      out.write("\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/delPersonServlet\" onsubmit=\"return checkSubmit3()\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">User Name </label><span id=\"usernamespan3\"></span>\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"username3\" name=\"username3\" size=\"25\" maxlength=\"15\" value=\"\" onblur=\"checkUsername3()\" align=\"center\" placeholder=\"type user name here\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-group\" style=\"text-align: center\">\r\n");
      out.write("\t<center>\r\n");
      out.write("              <input class=\"btn btn-primary\" type=\"submit\" value=\"SUBMIT\" />\r\n");
      out.write("              <input class=\"btn btn-default\" type=\"reset\" value=\"RESET\" />\r\n");
      out.write("    </center>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\"> \r\n");
      out.write("<center> <h3>Set Password</h3> </center>\r\n");
      out.write("\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/setPasswordServlet\" onsubmit=\"return checkPassword()\" method=\"post\">\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">User Name </label><span id=\"usernamespan4\"></span>\r\n");
      out.write("\t<input type=\"text\" class=\"form-control\" id=\"username4\" name=\"username4\" size=\"25\" maxlength=\"15\" value=\"\" onblur=\"checkUsername4()\" align=\"center\" placeholder=\"type user name here\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<label align=\"center\" style=\"text-align:center\">Password</label><span id=\"password\"></span>\r\n");
      out.write("\t<input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" size=\"25\" maxlength=\"15\" value=\"\" align=\"center\" placeholder=\"type your password here\">\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"form-group\" style=\"text-align: center\">\r\n");
      out.write("\t<center>\r\n");
      out.write("              <input class=\"btn btn-primary\" type=\"submit\" value=\"SUBMIT\" />\r\n");
      out.write("              <input class=\"btn btn-default\" type=\"reset\" value=\"RESET\" />\r\n");
      out.write("    </center>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<center><h4><a href=\"");
      out.print(request.getContextPath());
      out.write("/listInfoServlet\">Show Database</a></h4> </center>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
